### ISSUE TITLE
Old support link

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorWebsite#2]
Hi Miles,

For my own understanding of how the website works, does this line need to be updated?

https://github.com/emstoudenmire/ITensorWebsite/blob/cd6cc0a4f1b4ca46b20ae8bf9904ffc145c8348d/about.html#L54

When I go to the about page (https://itensor.org/about) the "Discuss" link at the top properly links to the new forum instead of the old forum, so it doesn't seem to be doing anything (i.e. if that line was relevant, I would have expected to navigate to the __old__ support site).

The same is true on the codes page (https://itensor.org/codes):

https://github.com/emstoudenmire/ITensorWebsite/blob/c1572c4383205e09b9a6a8168100c78d45d1c194/codes.html#L63

Is the code for navigation bar only specified somewhere else and not in the code for the individual pages, and if so why is the code for the navigation bar in those files at all?

Thanks!

**Comment by emstoudenmire** [comment]
Thanks for catching this! So what these files (codes.html, about.html) are now for is just to redirect visitors automatically to the new location of those pages, which have recently become `codes/index.html` and `about/index.html`. This was just a little change I made so that the urls could be things like `https://itensor.org/codes` without the `.html` extension. If you're curious how it works, these redirect files have a line:

    <meta http-equiv="Refresh" content="0; url=http://itensor.org/codes/" />

near the top that tells the browser to immediately navigate to a different page.

I did forget to update the Discuss link in these, though most people would never get to click that link because the page would redirect immediately. (I say most people because hypothetically someone could be using a browser where these automatic redirects don't happen, but I don't know of any modern browser that wouldn't do it.)

I'll make the fix thanks!

**Comment by mtfishman** [comment]
Got it, thanks for the explanation.

Is there a way to avoid repeating the navigation bar code across the different pages (for all the reasons of avoiding code duplication, i.e. it is error prone, harder to make updates, etc.)?

**Comment by mtfishman** [comment]
Obviously not a huge deal, partially I'm asking just to learn more about website code design. For example if this was Julia I would make a common function that generated the code for the navigation bar with some options to modify it depending on what page it was running on, not sure if there is a similar concept of functions or macros to generate code in html (besides literally writing a Julia function to generate html code which I guess is an option but probably overkill).

**Comment by emstoudenmire** [comment]
Yes you are hitting on a real pain point with web development, which is that html files aren't really code files that way, like where you could define functions and things. You can do that to a minor extent using Javascript but it's really not an ideal way to go.

So a much better way to go is to generate the html files using some other code, which could be in any language such as Julia. The generator could either be dynamic, like making the html at the very last minute as the user loads the site, which is how the ITensor C++ docs system works, or static where you run the generator on your own machine to build the site (make the html files) then these are uploaded to the server. That second, static approach is how the new generator Olivier and I are building is going to work. It's also how popular generators like Jekyll and Hugo work.

**Comment by mtfishman** [comment]
Gotcha, thanks for the explanation! Static code generation seems like a good way to go. So would your plan be to switch to that code generator for the ITensor website once it is ready?

**Comment by emstoudenmire** [comment]
Yes, possibly. I think definitely for the C++ docs just because the new system will be nicer and more secure. For the other pages each one is so different that it might not fit entirely in the statically-generated paradigm too well, which favors more like making a lot of pages with exactly the same header and footer and then content which is mostly text and images in the middle (a good example being, say, blog posts or the kind of content on tensornetwork.org). 

But it would be easy to add a feature to the HyTeX generator that lets you pass custom html through to the final page, so then it could be nice to use it to generate everything for the reasons you mentioned, like only having to define the header and footer in one place.
